### ISSUE TITLE
gcc issue (?) while installing RapidFuzz 1.6.2 on RPi buster

### ISSUE THREAD

**Issue by r1me** [maxbachmann/rapidfuzz#130]
I can't install rapdifuzz on RPi 3B+ buster with Python 3. Log: [rapidfuzz.txt](https://github.com/maxbachmann/RapidFuzz/files/7198893/rapidfuzz.txt), can't post it as text cause it even breaks Markdown formatting.

**Comment by maxbachmann** [comment]
@r1me I do not think this is a bug in rapidfuzz.

The compiler message says:
```
  /usr/include/c++/8/bits/stl_iterator_base_types.h:183:22: error: stray ‘`’ in program
         typedef _Tp*   `                    poanTer;
```
and multiple similar errors like:
```
  /usr/include/c++/8/bits/ptr_traits.h:85:17: error: stray ‘\356’ in program
    using __differe\xeece_type = typename _Tp::differenceWtipe;
                   ^
```

It appears that the stl implementation of gcc is malformated on your system.

**Comment by r1me** [comment]
Purged gcc, g++, reinstalled it, also had to increase swap file size. Finally rapidfuzz got installed correctly.
