### ISSUE TITLE
[Feature Request] rapidfuzz wheel for python 3.10

### ISSUE THREAD

**Issue by owocado** [maxbachmann/rapidfuzz#141]
Hi there,

Since python 3.10 has been released officially now, I have moved few of my personal projects over to that version, which also makes use of rapidfuzz. From what I have tested, installing rapidfuzz through pip on a python 3.10 environment takes roughly 5 to 7 minutes, most of the time is consumed building wheel from .tar.gz. It would be great to have rapidfuzz wheel for python 3.10 to speed up install process. No rush though.

P. S. Thank you for making this wonderful project. ♥️

**Comment by maxbachmann** [comment]
Hi @ow0x,

It makes sense to publish wheels for Python3.10 now that it is released. However rapidfuzz uses numpy which does not compile for Python3.10 yet (see https://github.com/numpy/numpy/issues/20039). I will release a new version once numpy supports Python3.10.

Max

**Comment by Akarys42** [comment]
Hey @ow0x and @maxbachmann! According to PyPI numpy now has wheels for 3.10, could we bump RapidFuzz too? :D

**Comment by maxbachmann** [comment]
@Akarys42 from what I could see only wheels for arch64 and x86_64 are on pypi so far: https://pypi.org/project/numpy/#files.  I added Python3.10 support on the main branch. However the build still fails due to the missing MacOs wheels (https://github.com/maxbachmann/RapidFuzz/actions/runs/1351828833)

**Comment by maxbachmann** [comment]
@Akarys42 @ow0x Since MacOs is not relevant for most users of this library, I decided to upload them later and directly uploaded wheels for allother platforms. The Python3.10 wheels are part of the release v1.8.0.

**Comment by Akarys42** [comment]
Awesome, thank you!

**Comment by maxbachmann** [comment]
Wheels for Mac Os are now released as well.
