### ISSUE TITLE
Why does my memory fail when I use rapidfuzz.process.extract

### ISSUE THREAD

**Issue by FlyEsi** [maxbachmann/rapidfuzz#154]
Hello, I am using rapidfuzz.process.extract every second. My RAM can't handle it. What should I do ? Are you using globals var?

**Comment by maxbachmann** [comment]
I could not reproduce this behavior. Could you provide me with a minimal reproducible example, which has this behavior?

**Comment by FlyEsi** [comment]
``
async def get_music(query):
   result = rapidfuzz.process.extract(query,dbs["audio_books"],scorer=rapidfuzz.fuzz.partial_ratio,limit=50)
   return query``

**Comment by maxbachmann** [comment]
What is the type of `dbs["audio_books"]`? Does the memory usage grow over time, or does it run out of memory on the first call?

**Comment by FlyEsi** [comment]
This is a list dbs = shelve.open ("books") there are 50,000 values
 1 request + 9mb to memory
10 requests 90 mbto memory
100 requests 900 mb to memory

**Comment by maxbachmann** [comment]
So you have a function like:
```
from rapidfuzz import process, fuzz
import random
import string
random.seed(18)

words = [''.join(random.choice(string.ascii_letters + string.digits) for _ in range(20)) for _ in range(50000)]
async def get(query):
    return process.extract(query, words, scorer=fuzz.partial_ratio, limit=50)
```

How is this function run? What do you do with the results? Could you change the example above to reproduce the behavior (so I can just copy paste and run it on my machine).

**Comment by FlyEsi** [comment]
Thanks is working 👍👍👍👍👍👍👍👍👍

**Comment by FlyEsi** [comment]
I don't sleep 48 hours . Thanks bro , you best
