### ISSUE TITLE
Add Android support

### ISSUE THREAD

**Issue by ZeroTwo00002** [maxbachmann/rapidfuzz#169]
Can someone help me.. noob here-.-

Preparing metadata (setup.py) ... done                Using legacy 'setup.py install' for pycryptodomex, since package 'wheel' is not installed.                      Using legacy 'setup.py install' for websockets, since package 'wheel' is not installed.                         Building wheels for collected packages: rapidfuzz         Building wheel for rapidfuzz (pyproject.toml) ... error                                                         ERROR: Command errored out with exit status 1:           command: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /data/data/com.termux/files/usr/tmp/tmpiuivpsqe          cwd: /data/data/com.termux/files/usr/tmp/pip-install-5vmqhgw6/rapidfuzz_612233c1feaf44049ef1ca5d00c5448f   Complete output (48 lines):                             running bdist_wheel                                     running build                                           running build_py                                        creating build                                          creating build/lib.linux-aarch64-3.10                   creating build/lib.linux-aarch64-3.10/rapidfuzz         copying src/rapidfuzz/levenshtein.py -> build/lib.linux-aarch64-3.10/rapidfuzz                                  copying src/rapidfuzz/__init__.py -> build/lib.linux-aarch64-3.10/rapidfuzz                                     copying src/rapidfuzz/fuzz.py -> build/lib.linux-aarch64-3.10/rapidfuzz                                         copying src/rapidfuzz/utils.py -> build/lib.linux-aarch64-3.10/rapidfuzz                                        copying src/rapidfuzz/string_metric.py -> build/lib.linux-aarch64-3.10/rapidfuzz                                copying src/rapidfuzz/process.py -> build/lib.linux-aarch64-3.10/rapidfuzz                                      running egg_info                                        writing src/rapidfuzz.egg-info/PKG-INFO                 writing dependency_links to src/rapidfuzz.egg-info/dependency_links.txt                                         writing top-level names to src/rapidfuzz.egg-info/top_level.txt                                                 reading manifest file 'src/rapidfuzz.egg-info/SOURCES.txt'                                                      reading manifest template 'MANIFEST.in'                 warning: no files found matching '*.txx' under directory 'src/rapidfuzz-cpp/rapidfuzz'                          warning: no previously-included files found matching 'src/rapidfuzz-cpp/rapidfuzz/process.hpp'                  warning: no previously-included files found matching 'src/rapidfuzz-cpp/rapidfuzz/process.txx'                  warning: no files found matching '*' under directory 'extern/variant'
  adding license file 'LICENSE'
  writing manifest file 'src/rapidfuzz.egg-info/SOURCES.txt'                                                      copying src/rapidfuzz/__init__.pyi -> build/lib.linux-aarch64-3.10/rapidfuzz                                    copying src/rapidfuzz/fuzz.pyi -> build/lib.linux-aarch64-3.10/rapidfuzz                                        copying src/rapidfuzz/process.pyi -> build/lib.linux-aarch64-3.10/rapidfuzz                                     copying src/rapidfuzz/string_metrics.pyi -> build/lib.linux-aarch64-3.10/rapidfuzz
  copying src/rapidfuzz/utils.pyi -> build/lib.linux-aarch64-3.10/rapidfuzz
  running build_ext                                       building 'rapidfuzz.cpp_process' extension              creating build/temp.linux-aarch64-3.10
  creating build/temp.linux-aarch64-3.10/src              creating build/temp.linux-aarch64-3.10/src/rapidfuzz-cpp
  creating build/temp.linux-aarch64-3.10/src/rapidfuzz-cpp/rapidfuzz                                              creating build/temp.linux-aarch64-3.10/src/rapidfuzz-cpp/rapidfuzz/details                                      aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Isrc/rapidfuzz-cpp/ -I/data/data/com.termux/files/usr/include/python3.10 -c src/cpp_process.cpp -o build/temp.linux-aarch64-3.10/src/cpp_process.o -O3 -std=c++11 -Wextra -Wall -Wconversion -g0 -DNDEBUG -DVERSION_INFO="1.5.1"                                                CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...
  building 'rapidfuzz.cpp_fuzz' extension                 aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Isrc/rapidfuzz-cpp/ -I/data/data/com.termux/files/usr/include/python3.10 -c src/cpp_fuzz.cpp -o build/temp.linux-aarch64-3.10/src/cpp_fuzz.o -O3 -std=c++11 -Wextra -Wall -Wconversion -g0 -DNDEBUG -DVERSION_INFO="1.5.1"
  CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...                    building 'rapidfuzz.cpp_string_metric' extension
  aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Isrc/rapidfuzz-cpp/ -I/data/data/com.termux/files/usr/include/python3.10 -c src/cpp_string_metric.cpp -o build/temp.linux-aarch64-3.10/src/cpp_string_metric.o -O3 -std=c++11 -Wextra -Wall -Wconversion -g0 -DNDEBUG -DVERSION_INFO="1.5.1"                                    CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...                    building 'rapidfuzz.cpp_utils' extension                aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Isrc/rapidfuzz-cpp/ -I/data/data/com.termux/files/usr/include/python3.10 -c src/cpp_utils.cpp -o build/temp.linux-aarch64-3.10/src/cpp_utils.o -O3 -std=c++11 -Wextra -Wall -Wconversion -g0 -DNDEBUG -DVERSION_INFO="1.5.1"                                                    CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...                    error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1        ----------------------------------------                ERROR: Failed building wheel for rapidfuzz            Failed to build rapidfuzz                               ERROR: Could not build wheels for rapidfuzz, which is required to install pyproject.toml-based projects

**Comment by maxbachmann** [comment]
The relevant error message is:
```
cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so
```
However I am not familiar with android and therefor do not know whether this is an unrelated problem, or whether the project does not compile properly on android.
