### ISSUE TITLE
How to get around the 498k line limit

### ISSUE THREAD

**Issue by DimIsaev** [maxbachmann/rapidfuzz#181]
how to get around the 498k line limit

487K  - Ok!
![image](https://user-images.githubusercontent.com/11172642/148425559-c3f7002f-e846-4955-ac7a-9c33143f15d7.png)

498K - Error!
![image](https://user-images.githubusercontent.com/11172642/148425635-b52ffc6b-d8c9-41d8-8e2f-dc7c831bc9a1.png)

Thanks

**Comment by maxbachmann** [comment]
Are you sure all rows include a string? This error sounds like one of the rows in the range `497000 - 498000` is a int and no string.

**Comment by DimIsaev** [comment]
> Are you sure all rows include a string? This error sounds like one of the rows in the range `497000 - 498000` is a int and no string.

big Thanks

```df['title'] = df.title.astype(str)```
solved problem
