### ISSUE TITLE
extract() calculates wrong scores

### ISSUE THREAD

**Issue by polikutinevgeny** [maxbachmann/rapidfuzz#186]
Hello! Thanks for the great library. I stumbled upon this problem where `extract` scores are inconsistent with its scorer.

```python
from rapidfuzz.fuzz import ratio
from rapidfuzz.process import extract

haystack = [
    'test',
    'test №',
]
needle = 'test №'

print(extract(needle, haystack, scorer=ratio))
# > [('test (test, test)', 100.0, 0), ('test (test, test) №', 100.0, 1)]

for i in haystack:
    print(ratio(needle, i))
# > 80.0
# > 100.0
```

**Comment by maxbachmann** [comment]
[`process.extract`](https://maxbachmann.github.io/RapidFuzz/Usage/process.html#extract) is using the processor [`utils.default_process`](https://maxbachmann.github.io/RapidFuzz/Usage/utils.html#default-process) by default to match the behavior of fuzzywuzzy/thefuzz. This preprocesses strings in the following way:
- removes all non alphanumeric characters
- trims whitespaces
- converts all characters to lower case

In your case the character '№' is not alphanumeric:
```python
>>> '№'.isalnum()
False
```
So 'test №' is preprocessed to 'test'. You can disable this by passing passing None as processor:
```python
>>> print(extract(needle, haystack, scorer=ratio))
[('test', 100.0, 0), ('test №', 100.0, 1)]

>>> print(extract(needle, haystack, scorer=ratio, processor=None))
[('test №', 100.0, 1), ('test', 80.0, 0)]
```

**Comment by polikutinevgeny** [comment]
Seems that I should have read the manual. 
This clears it up, thanks!
