### ISSUE TITLE
Get position using fuzz.partial_ratio

### ISSUE THREAD

**Issue by gamcoh** [maxbachmann/rapidfuzz#187]
Is there a way to get the position of the token found using `fuzz.partial_ratio` or something similar?

For instance:
```python
a = "a certain string"
s = "certain"

fuzz.partial_ratio_position(a, s)
>>> (2, 100.0) # position, match score
```

Or maybe the token that it matches with:
```python
a = "a certain string"
s = "cetain"

fuzz.partial_ratio_position(a, s)
>>> ("cetain", 92.30) # position, match score
```

**Comment by maxbachmann** [comment]
This is not supported so far. I am pretty sure someone already requested this already. However, I could not find the request.
I think a feature like this would be interesting. I am not sure what's the best way to implement this yet. From the two proposed API's I definitely prefer the first one, since it is faster to convert the index to a substring, than searching for the index based on the substring.
```python
>>> a = "a certain string"
>>> s = "cetain"
>>> res = fuzz.partial_ratio_position(s, a) # position, match score
>>> a[res[0]:res[0] + len(a)]
"certai"
```

I would propose the following API:

```python
>>> a = "a certain string"
>>> s = "cetain"
>>> res = fuzz.partial_ratio_position(s, a) # src_start=0, src_end=len(a), dest_start, dest_end, score
>>> a[res.dest_start:res.dest_end]
"certai"
```

This API would have the following advantages:
1) it handles shorter alignments, which can occur at end/start of the string.
2) it returns both the position in the source and destination string. This is helpful, since partial_ratio calculates the alignment of the shorter to the longer string. However, it is undefined whether the user passes the longer string as first or second parameter.

The result type could be a custom class, which behaves similar to a named tuple, which is more readable than access by index, but still allows unpacking into variables:
```python
>>> src_start, src_end, dest_start, dest_end, score = fuzz.partial_ratio_position(s, a)
```

**Comment by gamcoh** [comment]
How can I help implement it?

**Comment by maxbachmann** [comment]
The implementation of RapidFuzz is splitted into the C++ implementation and the Python wrapper.
You can find the C++ implementation here: https://github.com/maxbachmann/rapidfuzz-cpp and the Python wrapper here: https://github.com/maxbachmann/RapidFuzz.

As a first step this feature would need to be implemented in the C++ implementation. The current implementation of `partial_ratio` can be found here: https://github.com/maxbachmann/rapidfuzz-cpp/blob/main/rapidfuzz/fuzz.impl#L188-L190
You would have to:
1) modify `detail::partial_ratio_short_needle` and `detail::partial_ratio_long_needle` to return a struct, which includes the start and end positions. These functions already know these positions, but currently do not return them.
2) Add the function `partial_ratio_position`, which can be implemented similar to to the current implementation of `partial_ratio` and simply returns this struct
3) implement `partial_ratio` in terms of `partial_ratio_position`

In the Python wrapper you would need to perform the following modifications:
1) Write a wrapper function similar to https://github.com/maxbachmann/RapidFuzz/blob/81ac43cbf28f5c002f7c4c522a263f5042ed7f25/src/cython/cpp_fuzz.hpp#L15
2) Write the actual Python function similar to: https://github.com/maxbachmann/RapidFuzz/blob/81ac43cbf28f5c002f7c4c522a263f5042ed7f25/src/cython/cpp_fuzz.pyx#L120 the return value should be a `cdef class` behaving similar to a named tuple. This can be implemented in a similar way to https://github.com/maxbachmann/RapidFuzz/blob/81ac43cbf28f5c002f7c4c522a263f5042ed7f25/src/cython/distance/_initialize.pyx#L338
3) Add type hints for the function similar to https://github.com/maxbachmann/RapidFuzz/blob/81ac43cbf28f5c002f7c4c522a263f5042ed7f25/src/rapidfuzz/fuzz.pyi#L13 and import the function from https://github.com/maxbachmann/RapidFuzz/blob/main/src/rapidfuzz/fuzz.py
4) add a couple of tests in https://github.com/maxbachmann/RapidFuzz/blob/main/tests/test_fuzz.py
5) add the function to the documentation: https://github.com/maxbachmann/RapidFuzz/blob/main/docs/Usage/fuzz.rst

**Comment by maxbachmann** [comment]
@gamcoh do you plan to implement this? I would have time this weekend to implement the feature. But if you'd like to implement that, I have plenty of other things to work on as well.

**Comment by gamcoh** [comment]
Hello @maxbachmann,
Unfortunately I won't have time to implement this, sorry.
Would get back to you quickly if that changes.

**Comment by maxbachmann** [comment]
@gamcoh I implemented this feature on the main branch:
```python
>>> from rapidfuzz import fuzz
>>> a = "a certain string"
>>> s = "certain"
>>> fuzz.partial_ratio_alignment(s, a)
ScoreAlignment(score=100.0, src_start=0, src_end=7, dest_start=2, dest_end=9)
>>> fuzz.partial_ratio_alignment(a, s)
ScoreAlignment(score=100.0, src_start=2, src_end=9, dest_start=0, dest_end=7)
```

**Comment by maxbachmann** [comment]
This is part of v2.0.3
