### ISSUE TITLE
Test type hints using github actions

### ISSUE THREAD

**Issue by maxbachmann** [maxbachmann/rapidfuzz#189]
The type hints already had errors in multiple cases. It would make sense to validate them in the CI to prevent releases with invalid type hints.

**Comment by layday** [comment]
You might want to use https://mypy.readthedocs.io/en/latest/stubtest.html.

**Comment by maxbachmann** [comment]
That's exactly what I was looking for. Helped me find a bunch of errors in the type hints and is now part of the test suite: https://github.com/maxbachmann/RapidFuzz/pull/193 :partying_face:

**Comment by layday** [comment]
P.S. I noticed that you removed the re-exports from `__init__.pyi` in https://github.com/maxbachmann/RapidFuzz/commit/22a2ecbfa4395b6320c00e491a9ebdf0197d6133, meaning that typing users will need to import e.g. the process and fuzz modules individually. Was this intentional?

**Comment by maxbachmann** [comment]
No this was a mistake. I added them back.

**Comment by layday** [comment]
Great, thanks!

**Comment by layday** [comment]
Oh, they do have to be "re-exported" though for type checkers. In stub files, imports are private by default; to re-export an import you have to import it using `x as x`, e.g. `process as process`.
