### ISSUE TITLE
2.0.1 fails to build: Expected ':', found 'class'

### ISSUE THREAD

**Issue by yurivict** [maxbachmann/rapidfuzz#192]
```
Error compiling Cython file:
------------------------------------------------------------
...
)

from array import array

cdef extern from "rapidfuzz/details/types.hpp" namespace "rapidfuzz" nogil:
    cpdef enum class EditType:
              ^
------------------------------------------------------------

/disk-samsung/freebsd-ports/devel/py-rapidfuzz/work-py38/rapidfuzz-2.0.1/src/cython/cpp_common.pxd:23:15: Expected ':', found 'class'

Error compiling Cython file:
------------------------------------------------------------
...
# distutils: language=c++
# cython: language_level=3, binding=True, linetrace=True

from rapidfuzz_capi cimport RF_String, PREPROCESSOR_STRUCT_VERSION, RF_Preprocessor
from cpp_common cimport (
^
------------------------------------------------------------

/disk-samsung/freebsd-ports/devel/py-rapidfuzz/work-py38/rapidfuzz-2.0.1/src/cython/cpp_utils.pyx:5:0: 'cpp_common/is_valid_string.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# distutils: language=c++
# cython: language_level=3, binding=True, linetrace=True

from rapidfuzz_capi cimport RF_String, PREPROCESSOR_STRUCT_VERSION, RF_Preprocessor
from cpp_common cimport (
^
------------------------------------------------------------

/disk-samsung/freebsd-ports/devel/py-rapidfuzz/work-py38/rapidfuzz-2.0.1/src/cython/cpp_utils.pyx:5:0: 'cpp_common/convert_string.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# distutils: language=c++
# cython: language_level=3, binding=True, linetrace=True

from rapidfuzz_capi cimport RF_String, PREPROCESSOR_STRUCT_VERSION, RF_Preprocessor
from cpp_common cimport (
^
------------------------------------------------------------

/disk-samsung/freebsd-ports/devel/py-rapidfuzz/work-py38/rapidfuzz-2.0.1/src/cython/cpp_utils.pyx:5:0: 'cpp_common/hash_array.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# distutils: language=c++
# cython: language_level=3, binding=True, linetrace=True

from rapidfuzz_capi cimport RF_String, PREPROCESSOR_STRUCT_VERSION, RF_Preprocessor
from cpp_common cimport (
^
------------------------------------------------------------

/disk-samsung/freebsd-ports/devel/py-rapidfuzz/work-py38/rapidfuzz-2.0.1/src/cython/cpp_utils.pyx:5:0: 'cpp_common/hash_sequence.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# distutils: language=c++
# cython: language_level=3, binding=True, linetrace=True

from rapidfuzz_capi cimport RF_String, PREPROCESSOR_STRUCT_VERSION, RF_Preprocessor
from cpp_common cimport (
^
------------------------------------------------------------

/disk-samsung/freebsd-ports/devel/py-rapidfuzz/work-py38/rapidfuzz-2.0.1/src/cython/cpp_utils.pyx:5:0: 'cpp_common/conv_sequence.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
    validate_string(sentence, "sentence must be a String")
    return default_process_impl(sentence)


cdef bool default_process_capi(sentence, RF_String* str_) except False:
    proc_str = conv_sequence(sentence)
              ^
------------------------------------------------------------

/disk-samsung/freebsd-ports/devel/py-rapidfuzz/work-py38/rapidfuzz-2.0.1/src/cython/cpp_utils.pyx:44:15: 'conv_sequence' is not a constant, variable or function identifier

Error compiling Cython file:
------------------------------------------------------------
```

Python-3.8
cython-0.29.26
FreeBSD 13

**Comment by maxbachmann** [comment]
RapidFuzz requires `Cython==3.0.0a10`

https://github.com/maxbachmann/RapidFuzz/blob/4444f3411fcf04e0a9b74bf770c760828313a389/pyproject.toml#L9

How do you build the package, so the `pyproject.toml` is not picked up?

**Comment by yurivict** [comment]
It's a FreeBSD port build.

It'll wait for Cython-3 to be released then.

**Comment by maxbachmann** [comment]
This is an alpha version, which will not be picked up by pip by default. However you can force pip to install it using `pip install Cython==3.0.0a10`

**Comment by yurivict** [comment]
> [...] However you can force pip to install it using pip install Cython==3.0.0a10

Not in the port builder. It has fixed versions of all dependencies.

**Comment by maxbachmann** [comment]
> Not in the port builder. It has fixed versions of all dependencies.

I was not aware of this. In 2.0.0 I stopped shipping the generated sources and generate them using cython while installing, since I do not want to have them in my version history.

However I will probably run into similar problems when working on https://github.com/maxbachmann/RapidFuzz/issues/191. So maybe for now the best solution would be to generate the files as part of the build process and place them in the sdist.

**Comment by yurivict** [comment]
Yes, arbitrary dependency versions are only available in a Python environment.

Package builders always use fixed dependencies.

**Comment by maxbachmann** [comment]
@yurivict Btw RapidFuzz requires C++14 in recent versions. So:
```
USES=		compiler:c++11-lang python:3.6+
```
should probably be
```
USES=		compiler:c++14-lang python:3.6+
```

**Comment by yurivict** [comment]
> Btw RapidFuzz requires C++14 in recent versions. So:

Thanks!

I corrected this.

**Comment by maxbachmann** [comment]
@yurivict I released v2.0.2 which includes the transpiled cython files in the sdist and therefor does not require cython to be present when installing from it. This should fix your build problems.

**Comment by yurivict** [comment]
But 2.0.2 still has Cython in the .toml file. Is there a mistake?

**Comment by maxbachmann** [comment]
> But 2.0.2 still has Cython in the .toml file. Is there a mistake?

I left it in there on purpose, so when it automatically generates the files when they are not available. This is the case when building the wheels using cibuildwheel or when locally compiling (e.g. during development). Especially since the generator script currently does not support windows: https://github.com/maxbachmann/RapidFuzz/blob/main/src/cython/generate.sh. When the files are available (as they are in the sdist) cython will never be used:

https://github.com/maxbachmann/RapidFuzz/blob/main/src/cython/CMakeLists.txt#L1-L11

My best idea to handle this would be a patched `pyproject.toml` file in the sdist, which removes the unused Cython dependency  only in the sdist :thinking:
I am open to any better ideas.

**Comment by yurivict** [comment]
I updated the FreeBSD port.

Thank you for releasing the fix!
