### ISSUE TITLE
2.0.3 release results in wheel that is >50mb larger than 2.0.2

### ISSUE THREAD

**Issue by zeroaltitude** [maxbachmann/rapidfuzz#197]
pip install rapidfuzz: results in massively larger wheel (if building on cpython 3.9, amazon linux 2) than a few days ago (2.0.2).

**Comment by zeroaltitude** [comment]
Presumably this is due to the introduction of the seg wrapper? https://github.com/maxbachmann/RapidFuzz/commit/790467e7a160511b629b40f23c6786b62488a194

I would suggest that though this is awesome for a debug build, it might not be ideal for production use.

**Comment by zeroaltitude** [comment]
Hmmm. or perhaps it was the addition of the alignment data https://github.com/maxbachmann/RapidFuzz/commit/bf8dd83f2f42aa402144ac4650f6dd4f8824a71b

**Comment by maxbachmann** [comment]
Your first assumption is correct. I did mistakenly leave the build type as `release with debug symbols`. `v2.0.4` will have wheels without debug symbols again.

**Comment by zeroaltitude** [comment]
@maxbachmann Sorry to bug you -- thank you so much for the quick fix! Your build broke though and didn't push the new version to pypi. Just in case you missed it! Thanks again!

**Comment by maxbachmann** [comment]
@zeroaltitude yes I did not have the time to fix the build yet.
