### ISSUE TITLE
When using extractOne with score_cutoff, please return a (None, None, None) instead of None

### ISSUE THREAD

**Issue by John-Schreiber** [maxbachmann/rapidfuzz#200]
This would simplify using extractOne for lists with items with no matches.

**Comment by maxbachmann** [comment]
I will still need to think about this change. I understand this can be helpful when doing:
```python
a, b, c = extractOne(...)
```
However it has a couple of disadvantages as well:
- different api than fuzzywuzzy/thefuzz
- breaking change in rapidfuzz (can not be changed before v3.0.0)
- makes other legitimate use cases harder:
```python
if res := extractOne(...):
    a, b, c = res
```

In the long run I will probably guide people to this new API: https://github.com/maxbachmann/RapidFuzz/issues/188
The final API is not clear yet, but this will likely raise a ValueError for an empty result, but allows the user to pass an initial value similar to numpy (https://numpy.org/doc/stable/reference/generated/numpy.amax.html#numpy.amax):
```python
Compare(...).max() -> ValueError
Compare(...).max(initial=(None, 0, None)) -> (None, 0, None)
```

**Comment by John-Schreiber** [comment]
Thank you

**Comment by i30817** [comment]
I use : 

`a, b, c = extractOne(...) or (None, 0, None)`


Speaking of that, i'm not sure it's a good idea to return None for the number in the middle.

**Comment by maxbachmann** [comment]
> a, b, c = extractOne(...) or (None, 0, None)

Sounds like a good solution to @John-Schreiber's problem.
