### ISSUE TITLE
fuzz.token_set_ratio, a possible bug, at least not the same as doc

### ISSUE THREAD

**Issue by rocke-dong** [maxbachmann/rapidfuzz#204]
Dear Max Bachmann,

today, I nice to find your package, yes better than fuzzywuzzy. thanks!
I find a possible bug on fuzz.token_set_ratio which claims
"Compares the words in the strings based on unique and common words between them using fuzz.ratio"
to reproduce in 2.0.7

from rapidfuzz import fuzz， 
s20 = 'hey! rapidfuzz are doing sth very awesome, thanks'
s21 = 'rapidfuzz are doing awesome sth hey! hey'
print(fuzz.token_set_ratio(s20, s21))
print(fuzz.token_set_ratio(s21, s20))

Both print out 100. So it use partial_ratio in token_set_ratio. But I hope it use fuzz.ratio as its formal claim.
thanks!!

**Comment by maxbachmann** [comment]
The results of 100 is correct and the same result is returned by fuzzywuzzy as well. I agree this could probably be documented better. Improvements to the doc are welcome. You can find the docstring of `token_set_ratio` here: https://github.com/maxbachmann/RapidFuzz/blob/5b4da99b3878dd019c15e4c574c935281368e80f/rapidfuzz/cpp_fuzz.pyx#L265-L267

The following steps are performed by `token_set_ratio`
1) preprocess sequences by default (can be disabled using `processor=None`)
```
s20 = 'hey  rapidfuzz are doing sth very awesome  thanks'
s21 = 'rapidfuzz are doing awesome sth hey  hey'
```
1) split into words and remove duplicates:
```
{'thanks', 'doing', 'awesome', 'rapidfuzz', 'are', 'hey', 'sth', 'very'}
{'awesome', 'doing', 'rapidfuzz', 'are', 'hey', 'sth'}
```
2) finds intersection and different words between the sequences.
```
intersection = {'awesome', 'doing', 'rapidfuzz', 'are', 'hey', 'sth'}
diff1to2 = {'thanks', 'very'}
diff2to1 = {}
```
3) joins the words in sorted order
```
intersection = 'are awesome doing hey rapidfuzz sth'
diff1to2 = 'thanks very'
diff2to1 = ''
```
4) preprends intersection to the differences:
```
intersection = 'are awesome doing hey rapidfuzz sth'
diff1to2 = 'are awesome doing hey rapidfuzz sth thanks very'
diff2to1 = 'are awesome doing hey rapidfuzz sth'
```
4) calculate ratio for some combinations of intersection/difference and returns the max
```
fuzz.ratio(intersection, diff1to2)
fuzz.ratio(intersection, diff2to1)
fuzz.ratio(diff1to2, diff2to1)
```
In your example `intersection == diff2to1`, so the result is 100.

**Comment by rocke-dong** [comment]
Thanks for Max Bachmann.  I test also 2.0.8.
According to your detailed explanation, Currently fuzz.token_set_ratio has no difference with fuzz.partial_token_set_ratio.
```python
>>> from rapidfuzz import fuzz

>>> s1 = 'Max Bachmann creates rapidfuzz to doing sth very very awesome, thanks'
>>> s2 = 'very '
>>> s3 = 'Max Bachmann creates rapidfuzz to doing sth very awesome, thanks'

>>> fuzz.token_set_ratio(s1, s2)
>>> 100
>>> fuzz.token_set_ratio(s1, s3)
>>> 100
>>> fuzz.ratio(s1, s2)
>>> 13.513513513513509

>>> fuzz.partial_token_set_ratio(s1, s2)
>>> 100
>>> fuzz.partial_token_set_ratio(s1, s3)
>>> 100
>>> fuzz.partial_ratio(s1 , s3)
>>> 92.1875
```

**Comment by rocke-dong** [comment]
I think normally, "token set ratio" logic may be. 

1. orig input
s1 = 'Max Bachmann is very very awesome thanks'
s2 = 'very '
2. split into words and remove duplicates(this is the key feature of token set ratio, that's remove duplicates):
s1 = {'Max', 'Bachmann', 'is', 'very', 'awesome', 'thanks'}
s2 = {'very'}
3. joins the words in sorted order
s1 = 'awesome Bachmann is Max thanks very'
s2 = 'very'
4. calculate ratio
fuzz.ratio(s1, s2)

In my real work, I use python to write such a function for self usage.
I think your rapidfuzz is much faster than my purely python function.

Could you consider this token set ratio in rapid fuzz? I think this logic is clear and simple,  and useful. thanks!

**Comment by maxbachmann** [comment]
I reformatted your post to make it a bit more readable.

> According to your detailed explanation, Currently fuzz.token_set_ratio has no difference with fuzz.partial_token_set_ratio.

It does behave in a different way, since it used `fuzz.ratio` or `fuzz.partial_ratio` in the last step. Here is an example which leads to a different result:
```python
>>> from rapidfuzz import fuzz
>>> fuzz.token_set_ratio("test test1", "test test2")
90.0
>>> fuzz.partial_token_set_ratio("test test1", "test test2")
100.0
```

> Could you consider this token set ratio in rapid fuzz?

I want to keep the default behavior similar to `fuzzywuzzy`/`thefuzz`. I think the simplest solution would be to add an additional argument similar to `use_set_operations=True`. This would allow the user to select your proposed behavior using `use_set_operations=False`.

**Comment by rocke-dong** [comment]
> I reformatted your post to make it a bit more readable.
> 
> > According to your detailed explanation, Currently fuzz.token_set_ratio has no difference with fuzz.partial_token_set_ratio.
> 
> It does behave in a different way, since it used `fuzz.ratio` or `fuzz.partial_ratio` in the last step. Here is an example which leads to a different result:
> 
> ```python
> >>> from rapidfuzz import fuzz
> >>> fuzz.token_set_ratio("test test1", "test test2")
> 90.0
> >>> fuzz.partial_token_set_ratio("test test1", "test test2")
> 100.0
> ```
> 
> > Could you consider this token set ratio in rapid fuzz?
> 
> I want to keep the default behavior similar to `fuzzywuzzy`/`thefuzz`. I think the simplest solution would be to add an additional argument similar to `use_set_operations=True`. This would allow the user to select your proposed behavior using `use_set_operations=False`.

Yes, totally admire your idea to add use_set_operations. Your are master! thanks

**Comment by rocke-dong** [comment]
Sincerely wait for you to add this addtional argument `use_set_operations ` into token_set_ratio. It is nice to use `use_set_operations=False` to select my proposed behavior. thanks in advance!!

**Comment by i30817** [comment]
Please don't break the api. If you want another set token behavior that does not care about intersections, make a new function. The way i internalized token_set_ratio is 'if one of the strings is completely inside the other, it gives 100 and less if not'. I don't even know what 'use_set_operations=False' would even mean except that this idea would be completely wrong.

**Comment by maxbachmann** [comment]
> Please don't break the api.

I am not quite sure what your are talking about, This would not break the API in any way. Unless you rely on the fact that:
```
fuzz.token_set_ratio("test", "test2", use_set_operation=False)
```
raises a TypeError, which would be weird to say the least.

>  If you want another set token behavior that does not care about intersections, make a new function. 

Feel free to recommend another function name. I am happy to consider your Input ;)

**Comment by maxbachmann** [comment]
After thinking about this a bit more I think stuffing this into `token_set_ratio` is confusing, since I try to keep the whole `fuzz` module as similar in behavior to fuzzywuzzy as possible.

I might add a metric like this in the future, but it is not planned right now.
