### ISSUE TITLE
Mark locations of matches

### ISSUE THREAD

**Issue by archiif** [maxbachmann/rapidfuzz#205]
It would be useful if the library can return data that indicates where the matches are located in the text.
Something like: https://github.com/taleinat/fuzzysearch, but that library isn't very suitable for filtering and sorting through a list of text

**Comment by maxbachmann** [comment]
This is already possible for part of the API:
- `fuzz.ratio` -> [Indel.editops](https://maxbachmann.github.io/RapidFuzz/Usage/distance/Indel.html#editops) / [Indel.opcodes](https://maxbachmann.github.io/RapidFuzz/Usage/distance/Indel.html#opcodes)
- `fuzz.partial_ratio` -> [fuzz.partial_ratio_alignment](https://maxbachmann.github.io/RapidFuzz/Usage/fuzz.html#partial-ratio-alignment)
- `fuzz.*`: The other scorers in fuzz are more involved e.g. they sort the words before matching, so it is hard to return a location for them
- `distance.Levenshtein` -> [Levenshtein.editops](https://maxbachmann.github.io/RapidFuzz/Usage/distance/Levenshtein.html#editops) / [Levenshtein.opcodes](https://maxbachmann.github.io/RapidFuzz/Usage/distance/Levenshtein.html#opcodes)
- `distance.Indel` -> [Indel.editops](https://maxbachmann.github.io/RapidFuzz/Usage/distance/Indel.html#editops) / [Indel.opcodes](https://maxbachmann.github.io/RapidFuzz/Usage/distance/Indel.html#opcodes)
- `distance.Jaro`: Editops/Opcodes does not support transpositions yet. But at some point this will be added
- `distance.JaroWinkler`: Editops/Opcodes does not support transpositions yet. But at some point this will be added
- `distance.Hamming`: does not exist yet, but would be trivial to add.
