### ISSUE TITLE
score_cutoff ?

### ISSUE THREAD

**Issue by shubhamscifi** [maxbachmann/rapidfuzz#210]
### Discussed in https://github.com/maxbachmann/RapidFuzz/discussions/209

<div type='discussions-op-text'>

<sup>Originally posted by **shubhamscifi** April 13, 2022</sup>
The output should not be None in case 1 as the score_cutoff matches the fuzz.ratio. Why is it returning None in case1 but not in case2?
```
# case 1
a = "bc"
b = "bca"
print(rapidfuzz.fuzz.ratio(a, b))   # 80.0
print(process.extractOne(a, [b], scorer = rapidfuzz.fuzz.ratio, score_cutoff = 80.0))   # None

# case 2
a = "abcd"
b = "abce"
print(rapidfuzz.fuzz.ratio(a, b))   # 75.0
print(process.extractOne(a, [b], scorer= rapidfuzz.fuzz.ratio, score_cutoff = 75.0))    # ('abce', 75.0, 0)
```</div>

**Comment by maxbachmann** [comment]
This is improved in v2.0.9. It does now work correctly for your example. However there are probably some more edge cases in which similar problems exist.
