### ISSUE TITLE
Enhancement proposal: variant of process.cdist for all-vs-all

### ISSUE THREAD

**Issue by peterjc** [maxbachmann/rapidfuzz#211]
I would like to have single-input version of ``cdist`` which would be an optimised version of this:

```python
def all_vs_all(queries, **kwargs):
    return cdist(queries, queries, **kwargs)
```

It could benefit from an additional optional boolean argument ``symmetric`` to indicate if we can assume A vs B is the same as B vs A (not sure if that is true for all the scorers available, it is true for the ones I have been using).

Example:

```pycon
>>> from rapidfuzz.process import cdist
>>> from rapidfuzz.string_metric import levenshtein
>>> import numpy as np
>>> seqs = ["ACGTACGT", "ACGTTACGT", "ACGTAACGT", "ACGTACT"]
>>> cdist(seqs, seqs, scorer=levenshtein, dtype=np.int8, score_cutoff=3)
array([[0, 1, 1, 1],
       [1, 0, 1, 2],
       [1, 1, 0, 2],
       [1, 2, 2, 0]], dtype=int8)
```

would become:

```pycon
>>> from rapidfuzz.process import all_vs_all
>>> from rapidfuzz.string_metric import levenshtein
>>> import numpy as np
>>> seqs = ["ACGTACGT", "ACGTTACGT", "ACGTAACGT", "ACGTACT"]
>>> all_vs_all(seqs, scorer=levenshtein, dtype=np.int8, score_cutoff=3, symmetric=True)
array([[0, 1, 1, 1],
       [1, 0, 1, 2],
       [1, 1, 0, 2],
       [1, 2, 2, 0]], dtype=int8)
```

**Comment by maxbachmann** [comment]
I already provide a way for scorers to flag that they are symmetric using the C-API. E.g. Levenshtein is symmetric as long as the insertion cost and deletion cost are the same: https://github.com/maxbachmann/RapidFuzz/blob/174aaf7a7c5baadfc8ab3297bfc7fa2c883fd517/rapidfuzz/distance/Levenshtein.pyx#L420-L427

This is used by `cdist` to select the optimized implementation you describe:

https://github.com/maxbachmann/RapidFuzz/blob/174aaf7a7c5baadfc8ab3297bfc7fa2c883fd517/rapidfuzz/cpp_process_cdist.pyx#L273-L280

So your implementation of `all_vs_all` already performs the optimization you expect it to perform ;)

I thought about adding [`pdist`](https://docs.scipy.org/doc//scipy-1.2.3/reference/generated/scipy.spatial.distance.pdist.html) as well, which would save 50% of the memory for the results. However I was not sure how to handle scorers that are not symmetric:
1) raise a ValueError
2) just behave like they are symmetric

**Comment by peterjc** [comment]
It sounds like I can just use ``cdist`` as it is, so I'll close my issue. I didn't dig deep enough into the source code - nice 👍 

I can see some value in adding ``pdist`` so happy for you to morph this issue to cover that instead?

Thank you!
