### ISSUE TITLE
Could you please provide compatibility with Cython 0.29.x?

### ISSUE THREAD

**Issue by mgorny** [maxbachmann/rapidfuzz#221]
I've been trying to package RapidFuzz for Gentoo. Unfortunately, we're nowhere near close to being ready to switch to Cython 3.x, so the requirement on alpha version of Cython makes it impossible for us to package it. Could you please consider providing compatibility with the current release versions of Cython?

**Comment by maxbachmann** [comment]
What is the source you use for packaging? Do you package directly from git by tag, github releases, the sdist on PyPI?

**Comment by mgorny** [comment]
We use GitHub archives. Unfortunately, the PyPI releases don't include tests.

**Comment by maxbachmann** [comment]
It is probably hard to switch to Cython 0.29.x, since I use quite a few Cython 3 features, since I added some things I needed to Cython. Some other package maintainers had a similar problem, but did use the sdist. For this reason I already add the generated versions of the Cython files to the sdist before publishing. I think the best way would be to add a separate `release` branch, which gets a newly generated version of all Cython files on release and which is used as basis of tags, github releases and PyPi releases. This way Cython is no build requirement for the released versions.

**Comment by mgorny** [comment]
I suppose that would work for me, or simply including the full set of files in sdist. We generally prefer to regenerate Cython files locally (since we sometimes end up backporting patches to Cython) but I suppose we can live without that for now.

**Comment by maxbachmann** [comment]
> or simply including the full set of files in sdist

Assuming this would only require me to add the `tests/` directory to the sdist, this would probably be the simplest option.

**Comment by maxbachmann** [comment]
This should be fixed by https://github.com/maxbachmann/RapidFuzz/commit/1c583e8118cc1bab8f91224d2bd57908a94347e4, which includes the tests into the sdist. In addition it removes the Cython dependency for the sdist build, since the sdist includes the generated Cython files.

**Comment by maxbachmann** [comment]
@mgorny the latest versions of both jarowinkler and rapidfuzz do now include the tests in their sdist. So you should be able to use the sdist as basis for your package now. Let me know in case something else is missing from the sdist.

**Comment by mgorny** [comment]
Thanks. Unfortunately, the pregenerated files don't work on Python 3.11 which is a complete blocker for us, given that the old Levenshtein package we're trying to replace works fine on Python 3.11 and has revdeps that require it.

**Comment by maxbachmann** [comment]
There is not much I can do about this until there is a new Cython release.

**Comment by mgorny** [comment]
Well, I suppose you could run Cython from git ;-).

**Comment by maxbachmann** [comment]
> Well, I suppose you could run Cython from git ;-).

it is actually not possible to use the master version of Cython without additional patches. In fact I did this in the past, which lead to the following bug: https://github.com/maxbachmann/RapidFuzz/issues/95

**Comment by maxbachmann** [comment]
I do now use Cython 3.0a11 which should work with Python3.11. Apparently Cython will release the first beta for 3.0 soon, so hopefully there will be a final release for Cython 3 soon as well. I understand that this complicates packaging for some package managers which do not provide the pre release versions of Cython. However I do not think it is worth the effort for me. In case you find only a small amount of changes to be required to support Cython 0.29 I would be happy to accept a PR with these changes.

**Comment by maxbachmann** [comment]
> I do now use Cython 3.0a11 which should work with Python3.11

I do now provide wheels for Python3.11 as well, so it appears to work
