### ISSUE TITLE
fails to build on armv7

### ISSUE THREAD

**Issue by maxbachmann** [maxbachmann/rapidfuzz#223]
Similar to https://github.com/maxbachmann/RapidFuzz/issues/195 and https://github.com/maxbachmann/RapidFuzz/issues/215 cmake fails to compile on armv7 as reported on stackoverflow: https://stackoverflow.com/questions/72496394/rapidfuzz-install-issues-caused-by-cmake.

**Comment by maxbachmann** [comment]
This is fixed in the latest release

**Comment by RSwarnkar** [comment]
Oh My, this cmake issue plagues the many packages. :(
