### ISSUE TITLE
AttributeError: module 'rapidfuzz.fuzz' has no attribute 'partial_ratio_alignment'

### ISSUE THREAD

**Issue by OleksiyAnokhin** [maxbachmann/rapidfuzz#226]
Good day, @maxbachmann . I get this error

`AttributeError: module 'rapidfuzz.fuzz' has no attribute 'partial_ratio_alignment'` working with [rapidfuzz.fuzz](https://maxbachmann.github.io/RapidFuzz/Usage/fuzz.html)

All other 10 functions work well, but `partial_ratio_alignment` gives me an error. Thanks!

**Comment by maxbachmann** [comment]
Where do you run into this issue? For me it works fine to import the function:
```python
from rapidfuzz import fuzz
fuzz.partial_ratio_alignment(...)
```
and the type hints work properly in my IDE (VS Code)

**Comment by OleksiyAnokhin** [comment]
@maxbachmann, 

    print(rapidfuzz.__version__)

Version `1.9.1`

Example

```
from rapidfuzz import fuzz
fuzz.partial_ratio_alignment('Alex', 'Shmalex')
```
Error
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-9c8803aa1870> in <module>
      1 from rapidfuzz import fuzz
----> 2 fuzz.partial_ratio_alignment('Alex', 'Shmalex')

AttributeError: module 'rapidfuzz.fuzz' has no attribute 'partial_ratio_alignment'
```

10 other functions work. Example below. 

```
from rapidfuzz import fuzz
fuzz.partial_ratio('Alex', 'Shmalex')
```
Output

`85.71428571428571`

**Comment by maxbachmann** [comment]
Do you use the lastest version of rapidfuzz? At least for me this works fine:
```
>>> from rapidfuzz import fuzz
>>> fuzz.partial_ratio_alignment('Alex', 'Shmalex')
ScoreAlignment(score=85.71428571428572, src_start=0, src_end=4, dest_start=4, dest_end=7)
```

**Comment by OleksiyAnokhin** [comment]
@maxbachmann , updated the comment. Version `1.9.1` via `pip install rapidfuzz`. The latest one is 2.0.12, but I do not receive it.

**Comment by maxbachmann** [comment]
`partial_ratio_alignment` was added in v2.0.3: https://github.com/maxbachmann/RapidFuzz/releases/tag/v2.0.3

**Comment by OleksiyAnokhin** [comment]
@maxbachmann , thanks, than something is on my side, will try to fix it

    Requirement already satisfied: rapidfuzz in c:\users\user\anaconda3\lib\site-packages (2.0.11)

However, I still get 

`print(rapidfuzz.__version__)` as `1.9.1`

**Comment by maxbachmann** [comment]
You should look at:
```
print(rapidfuzz.__path__)
```

**Comment by OleksiyAnokhin** [comment]
Uninstalled the library and installed again. Work now, thanks!
