### ISSUE TITLE
Behaviour of cdist when edit distance exceeds score_cutoff

### ISSUE THREAD

**Issue by peterjc** [maxbachmann/rapidfuzz#235]
Quoting https://maxbachmann.github.io/RapidFuzz/Usage/process.html#cdist

> * score_cutoff (Any, optional) – Optional argument for a score threshold. When an edit distance is used this represents the maximum edit distance and matches with a distance <= score_cutoff are inserted as -1. When a normalized edit distance is used this represents the minimal similarity and matches with a similarity >= score_cutoff are inserted as 0. Default is None, which deactivates this behaviour.

This gives the impression that if ``score_cutoff`` is used with an edit distance (meaning this is an upper bound), when the score exceeds it the flag value ``-1`` is returned.

However, other parts of the documentation suggest ``score_cutoff + 1`` is returned. For example, Hamming or Levenshtein distance. See the ``max=`` argument to ``rapidfuzz.string_metric.levenshtein`` as documented at https://maxbachmann.github.io/RapidFuzz/Usage/string_metric.html#rapidfuzz.string_metric.levenshtein

> * max (int or None, optional) – Maximum distance between s1 and s2, that is considered as a result. If the distance is bigger than max, max + 1 is returned instead. Default is None, which deactivates this behaviour.

e.g. using v2.1.2

```
>>> from rapidfuzz.process import cdist
>>> from rapidfuzz.string_metric import levenshtein
>>> import numpy as np
>>> seqs = ["ACGTACGT", "ACGTTACGT", "ACGTAACGT", "ACGTACT", "X"]
>>> cdist(seqs, seqs, scorer=levenshtein, dtype=np.int8, score_cutoff=3)
array([[0, 1, 1, 1, 4],
       [1, 0, 1, 2, 4],
       [1, 1, 0, 2, 4],
       [1, 2, 2, 0, 4],
       [4, 4, 4, 4, 0]], dtype=int8)
```

If many/all of the provided edit distances use ``score_cutoff + 1`` then perhaps the ``cdist`` documentation is misleading?

**Comment by peterjc** [comment]
This is a behaviour change from v1.9.1 to v2.0.0, quoting the change log:

> when the result of string_metric.levenshtein or string_metric.hamming is below max they do now return max + 1 instead of -1

```
$ python
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:52) 
[Clang 13.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from rapidfuzz.process import cdist
>>> from rapidfuzz.string_metric import levenshtein
>>> import numpy as np
>>> seqs = ["ACGTACGT", "ACGTTACGT", "ACGTAACGT", "ACGTACT", "X"]
>>> cdist(seqs, seqs, scorer=levenshtein, dtype=np.int8, score_cutoff=3)
array([[ 0,  1,  1,  1, -1],
       [ 1,  0,  1,  2, -1],
       [ 1,  1,  0,  2, -1],
       [ 1,  2,  2,  0, -1],
       [-1, -1, -1, -1,  0]], dtype=int8)
>>> import rapidfuzz
>>> rapidfuzz.__version__
'1.9.1'
```

```
$ python
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:52) 
[Clang 13.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from rapidfuzz.process import cdist
>>> from rapidfuzz.string_metric import levenshtein
>>> import numpy as np
>>> seqs = ["ACGTACGT", "ACGTTACGT", "ACGTAACGT", "ACGTACT", "X"]
>>> cdist(seqs, seqs, scorer=levenshtein, dtype=np.int8, score_cutoff=3)
array([[0, 1, 1, 1, 4],
       [1, 0, 1, 2, 4],
       [1, 1, 0, 2, 4],
       [1, 2, 2, 0, 4],
       [4, 4, 4, 4, 0]], dtype=int8)
>>> import rapidfuzz
>>> rapidfuzz.__version__
'2.0.0'
```

It looks like the documentation for ``cdist`` does just need updating to match?

**Comment by maxbachmann** [comment]
Yes this was a change in behavior of the string metric. `cdist` really does not care about it, since it just passes the score_cutoff to the string metric. I clarified this in the documentation by removing these confusing bits: https://github.com/maxbachmann/RapidFuzz/commit/fde0a662fafbf50a6aab53676002f8fd6bbd33a8

**Comment by peterjc** [comment]
That is clear now, thank you - closing issue.

**Comment by maxbachmann** [comment]
As a note you should change:
```python
from rapidfuzz.string_metric import levenshtein
...
scorer=levenshtein
```
to something like
```python
from rapidfuzz.distance import Levenshtein
...
scorer=Levenshtein.distance
```

The whole string_metric module is deprecated since v2.0.0 and moving forward all metrics will be added in the distance namespace

**Comment by peterjc** [comment]
Thank you - I've updated my imports accordingly.
