### ISSUE TITLE
Docs have disappeared

### ISSUE THREAD

**Issue by jonathan-kosgei** [maxbachmann/rapidfuzz#280]
There used to be lengthy descriptions on [this page](https://maxbachmann.github.io/RapidFuzz/Usage/process.html) that were a very helpful reference. However they seem to have disappeared over the past week.

![image](https://user-images.githubusercontent.com/6712914/194698852-a6c346c7-8583-4b1a-ae50-01b19da886a7.png)

**Comment by maxbachmann** [comment]
Thanks for bringing this up. A bug in the main branch lead to the doc generation being unable to import any of the help texts.
This is fixed now.
