### ISSUE TITLE
Fuzzy search by prefix?

### ISSUE THREAD

**Issue by RasecMalkic** [maxbachmann/rapidfuzz#281]
Good day, which would be the best approach/scorer to use in order to have better results when trying to match in same order (by prefix)? for example

For example If I search the value "38050" within a list that contains "358", the result is ('358', 72.0, 8) because 3, 5 and 8 are present in 38050, but for me is not of interest since 3, 5 and 8 are in different order. Would be a match for me if the choice found would be 380XX, that has similarity in prefix compared with 38050. 

The issue is related with this question I made yesterday and they suggest to use another scorer or try differents.

https://stackoverflow.com/questions/74093719/how-to-make-fuzzy-search-between-lists-showing-matches-and-not-found-elements

Thanks in advance.

**Comment by maxbachmann** [comment]
what would a scorer do when matching by prefix. I guess a simple solution based solely on the common prefix would be
```python
from os.path import commonprefix

query = "38050"
choices = ["358", "38011"]

best_choice = None
longest_prefix = 0
for choice in choices:
    prefix_len = len(os.path.commonprefix([query, choice]))
    if prefix_len > longest_prefix:
        best_choice = choice
```

**Comment by RasecMalkic** [comment]
Thanks so much for your solution idea. I was in the way of suggestions received in SO, but if you, as the creator of rapidfuzz, suggest to use commonprefix library, so what more can I say? hehe

I'll try to adapt you example to my 3 lists inputs since I have thousands of values to search within a bigger list of choices. Hope get good perfomance.

**Comment by maxbachmann** [comment]
I was not really sure what kind of metric you wanted to have. Did I understand it right, that you simply want to find the string with the longest common prefix?

Some other string matching libraries have this kind of metric under the name `Prefix` distance. It would be simple to add this metric in rapidfuzz as well. From a quick benchmark an implementation in `rapidfuzz` would be around 10x faster when directly calling the scorer and around 50x faster when using it for a list through the `process` module.

**Comment by RasecMalkic** [comment]
Yes, I want to find the string with the longest common prefix for all the strings in list "to_search" comparing with the strings in list "choices". The string to search could have a length minor, equal or larger than the best choice within "choices".

```
choices = [
        '237','17218','124622','334','124624','124','1246','1876','358',
        '33751','33679','599','61','230','31','65','17215','1','124623'
    ]

to_search = ['18763044','187635','23092','3162','38050','33','49185','51078','1246','1721']
```


for above input lists, my expected output would be

```
TO SEARCH   BEST CHOICE		
187630441   1876		
187635	    1876		
23092	    230		
3162	    31		
38050	    NOT FOUND		
33	    334		   ## Best choice is 334 since is the shortest between 334, 33679 and 33751
49185	    NOT FOUND	
51078	    NOT FOUND	
1246	    1246		
1721	    17215          ## Best choice is 17215 since in ascending order 17215 is the first between 17215 and 17218
```

**Comment by RasecMalkic** [comment]
> I was not really sure what kind of metric you wanted to have. Did I understand it right, that you simply want to find the string with the longest common prefix?
> 
> Some other string matching libraries have this kind of metric under the name `Prefix` distance. It would be simple to add this metric in rapidfuzz as well. From a quick benchmark an implementation in `rapidfuzz` would be around 10x faster when directly calling the scorer and around 50x faster when using it for a list through the `process` module.

Based on your comment I found a library called `textdistance` that seems to have 30+ algorithms included one for prefix. If you have time enough, may you show how to add it in rapidfuzz? would be like define an own scorer with library `textdistance` and the call that scorer with process module?

**Comment by maxbachmann** [comment]
Yes textdistance is one of the libraries I was referring to.  Generally textdistance is more of a reference implementation of algorithms which is more focused on simplicity than performance. In theory you could create a scorer based on this, but it is probably not worth the effort, since it would be more complex than simply writing the for loop yourself.
I should be able to add a fast implementation of `Prefix`/`Postfix` to rapidfuzz tomorrow.

**Comment by RasecMalkic** [comment]
> Yes textdistance is one of the libraries I was referring to. Generally textdistance is more of a reference implementation of algorithms which is more focused on simplicity than performance. In theory you could create a scorer based on this, but it is probably not worth the effort, since it would be more complex than simply writing the for loop yourself. I should be able to add a fast implementation of `Prefix`/`Postfix` to rapidfuzz tomorrow.

Actually I tested to create a scorer using 'textdistance' but I failed in the attempt. It would be great to see the addition for Prefix/Postfix to rapidfuzz, surely will be the faster option. Thanks for the help.

**Comment by maxbachmann** [comment]
I did implement this, but currently can not release a new version due to some build issues. If you want to use it right now, you can build the project locally. I hope I find the time to debug the build issues sometimes next week.

**Comment by RasecMalkic** [comment]
Not sure how to build it or what tools are needed. I think better to wait when you could add it. Thank you

**Comment by maxbachmann** [comment]
I fixed the build issue and made a new release which adds `rapidfuzz.distance.Prefix`.

**Comment by RasecMalkic** [comment]
Thanks for your addition of distance.prefix. I've tried with extraceOne() and it works fine, but I have an issue when I tried with actual data data that compares 2 lists of more than 1000 values. I needed to stop after 12 min

`rows` is a list that contains more than 2100 sublists, and `choices` is a list  with 2500 strings. The loop below tries to find the best choice for each string in position 5 of each sublist comparing with choices.
```
>>> for query in rows:
...     for choice in choices:
...         best_choice =  extractOne(query[5], choices, scorer=Prefix.similarity, score_cutoff=3)
...         out.append(best_choice)
...
^CTraceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "process_cpp_impl.pyx", line 620, in rapidfuzz.process_cpp_impl.extractOne
  File "process_cpp_impl.pyx", line 496, in rapidfuzz.process_cpp_impl.extractOne_list
  File "process_cpp_impl.pyx", line 455, in rapidfuzz.process_cpp_impl.extractOne_list_i64
KeyboardInterrupt
>>>
```

**Comment by maxbachmann** [comment]
Why do you iterate over choices? It should just be:
```python
for query in queries:
    best_choice =  extractOne(query, choices, scorer=Prefix.similarity, score_cutoff=3)
    out.append(best_choice)
```

**Comment by RasecMalkic** [comment]
> Why do you iterate over choices? It should just be:
> 
> ```python
> for query in queries:
>     best_choice =  extractOne(query, choices, scorer=Prefix.similarity, score_cutoff=3)
>     out.append(best_choice)
> ```

You're very right. Not sure why I did that. Now trying the correct loop as you suggested, within the whole script, it takes 0.75 seconds. This is 12 faster than script that contains a loop using `textdistance`.

Thanks so much for your help and time.

rapidfuzz	                         0.75272    seconds
textdistance	                 9.02997    seconds
rapidfuzz/textdistance	11.99633
