### ISSUE TITLE
matching with Tabular Data

### ISSUE THREAD

**Issue by shiv-acharii** [maxbachmann/rapidfuzz#283]
Let's assume that I have a tabular Data in excel or Pandas Data frame, something like below :

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/shachari/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/shachari/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

TYPE | NO | UNIT | FAMILY
-- | -- | -- | --
Change | 84785 | BU | WIN
Tracking | 84778 | ER | IOS
Status | 84778 | ER | IOS
Ready to Ship | 84778 | BU | WIN
Change | 84785 | CPBU | WIN

</body>

</html>

And user Enters below dataFrame
<html>
<body>

Change | 84785 | BU | WIN
-- | -- | -- | --

</body>
</html>

now it should give me a Output like below :
The Top 2 Matching entries are
Top 1: 100% match and Top 2: 90% match
<html>
<body>

TYPE | NO | UNIT | FAMILY
-- | -- | -- | --
Change | 84785 | BU | WIN
Change | 84785 | CPBU | WIN

</body>
</html>

**So what is the best way to use RapidFuzz for Tabular Data like above sample Example?**
Sould I Merge all tabular data as a single string like :

"Change 84785  BU  WIN" 

or I can have match at tabular level as well ???

**Comment by maxbachmann** [comment]
I would match this in multiple separate steps:
```python
from rapidfuzz.process import cdist

type_score = cdist([query["TYPE"]], choices["TYPE"])
family_score = cdist([query["FAMILY"]], choices["FAMILY"])
...
```
This gives you a numpy array of the similarities for each of the separate rows. This has the following advantages:
- allows you to combine the scores in whichever way you want
- allows you to use different scorers for the rows

In addition consider to replace user input fields with drop down lists where sensible. E.g. for the `FAMILY` field you should have a finite number of possible inputs, so a drop down list of all possible inputs would remove the need to use fuzzy string matching for the field.
