### ISSUE TITLE
Different scores when using same strings with fuzz.WRatio() and process.cdist

### ISSUE THREAD

**Issue by steve-solun** [maxbachmann/rapidfuzz#285]
Here is what I am trying to do:

```
from rapidfuzz import fuzz, process

fuzz.WRatio("an ecs service for", "chagan-service-2")

> 64.70588235294117

process.cdist(queries=["an ecs service for"], choices=["chagan-service-2"], score_cutoff=50, scorer=fuzz.WRatio)

> array([[52.941177]], dtype=float32)
```

Why do I get different scores? 
@Tenzer @mgorny @Phxntxm @glynn-zenefits @henryiii

**Comment by maxbachmann** [comment]
`fuzz.WRatio` preprocesses strings by default, while `process.cdist` does not. You can achieve the same results using:
```python
>>> fuzz.WRatio("an ecs service for", "chagan-service-2", processor=None)
52.94117647058824
```
or
```python
>>> process.cdist(queries=["an ecs service for"], choices=["chagan-service-2"], score_cutoff=50, scorer=fuzz.WRatio, processor=utils.default_process)
array([[64.70588]], dtype=float32)
```

In addition please do not tag unrelated users in issues.

**Comment by steve-solun** [comment]
And what about this @maxbachmann 

`fuzz.ratio("an ecs service for", "chagan-service-2")`
> 52.94.....

`process.extract(query="an ecs service for", choices=["chagan-service-2"], score_cutoff=30, scorer=fuzz.ratio)`
> 64.705....

**Comment by maxbachmann** [comment]
This is the same issue in reverse. `fuzz.ratio` does not preprocess strings by default, but `process.extract` does:
```python
>>> fuzz.ratio("an ecs service for", "chagan-service-2", processor=utils.default_process)
64.70588235294117
```
and
```python
>>> process.extract(query="an ecs service for", choices=["chagan-service-2"], score_cutoff=30, scorer=fuzz.ratio, processor=None)
[('chagan-service-2', 52.94117647058824, 0)]
```

**Comment by steve-solun** [comment]
Thank you so much dear Max!
