### ISSUE TITLE
How to pass the score_cutoff to the rapidfuzz.distance.JaroWinkler.normalized_similarity when inside process.extract?

### ISSUE THREAD

**Issue by steve-solun** [maxbachmann/rapidfuzz#286]
Please advise how can I pass the score_cutoff to:

`process.extract(query="cha", choices=["chagan"], scorer=rapidfuzz.distance.JaroWinkler.normalized_similarity, score_cutoff=0.0, processor=None)`

It returns an empty list `[]`

But when I am running:
`process.extract(query="cha", choices=["chagan"], scorer=rapidfuzz.distance.JaroWinkler.normalized_similarity, processor=None)`
I am getting: `[('chagan', 0.11666666666666659, 0)]`

**Comment by maxbachmann** [comment]
This is a bug I fixed in https://github.com/maxbachmann/RapidFuzz/commit/735f7019e517fbfac25de395dcdb3a9b456b26d7.
You should be able to use `JaroWinkler.similarity` instead, which leads to the same results as `JaroWinkler.normalized_similarity` without this bug.

**Comment by steve-solun** [comment]
Great! Thanks a lot!

**Comment by maxbachmann** [comment]
I will release a fixed version later today.

**Comment by steve-solun** [comment]
Great @maxbachmann! Thanks a lot! It helps a lot.
