### ISSUE TITLE
rapidfuzz_sse2.hpp seems to require SSSE3

### ISSUE THREAD

**Issue by jcelerier** [maxbachmann/rapidfuzz#287]
It includes 

    #include <tmmintrin.h>

which is the ssse3 header ; this looks like an error as this implies SSE3 support, yet there is some commented code in that file (`
    /* todo use when sse3 available`). On some platforms it may give an actual error: my compiler tells me

    include/compat/tmmintrin.h:11:2: error: "SSSE3 instruction set not enabled"

**Comment by maxbachmann** [comment]
Yes, this include was added by mistake.

**Comment by maxbachmann** [comment]
This is fixed on `main`. I will likely release a new version later today.

**Comment by jcelerier** [comment]
thanks !
