### ISSUE TITLE
how to increase speed for 1M records

### ISSUE THREAD

**Issue by shiv-acharii** [maxbachmann/rapidfuzz#290]
i have close to 1 million records, and I see its taking lot of time to give output, whats the best way to increase the speed?
do we have some vectorization or dimensionality reduction techniques here?

**Comment by maxbachmann** [comment]
Some questions regarding your problem:
- do you need to compare one string to 1 million strings or N string to 1 million strings?
- what is your usual string length? is it usually < 64 characters?
- is there a specific similarity algorithm you prefer on your problem?
- do you have a small example how you are currently calling rapidfuzz?
