### ISSUE TITLE
ENH: use `functools.lru_cache` to speed up

### ISSUE THREAD

**Issue by Zeroto521** [maxbachmann/rapidfuzz#292]
Levenshtein distance algorithm can't be vectorized.
So the calculation would be very slow in large data.

An idea to speed up is using the cache.
Use the `accumulate` case to show the cache.

```python
def accumulate(x):
    return sum(range(x))
```

`accumulate(100000000)` needs 5s no matter if it is the first time running or the second time running in my local without `lru_cache`.

```python
from functools import lru_cache

@lru_cache
def accumulate(x):
    return sum(range(x))
```

After adding `lru_cache`, the first running `accumulate(100000000)` still needs 5s.
But the second time running `accumulate(100000000)` needs **0s**.

closed to https://github.com/seatgeek/thefuzz/issues/42

**Comment by maxbachmann** [comment]
For large amounts of data you should not directly call the corresponding scorer:
```python
from rapidfuzz.distance import Levenshtein

for choice in choices:
    Levenshtein.distance(query, choice)
```
instead you should use the process module:
```python
from rapidfuzz import process
from rapidfuzz.distance import Levenshtein

process.cdist([query], choices, scorer=Levenshtein.distance)
```

I do not think duplicates of both `query` and `choice` are very common. So chances are they would be evicted from the cache before you reach a duplicate.
