### ISSUE TITLE
Identical calls to cdist return different values

### ISSUE THREAD

**Issue by maximz** [maxbachmann/rapidfuzz#300]
Thanks for this library. Seeing an odd issue:

```python
import numpy as np
import rapidfuzz

arr = np.array(["ABCD", "ABCC", "ABCDE", "FABCDE"])
for _ in range(3):
    # weights set to (insertion=1, deletion=1, substitution=1)
    print(
        rapidfuzz.process.cdist(
            arr, arr, scorer=rapidfuzz.distance.Levenshtein.distance, weights=(1, 1, 1)
        )
    )

print(f"rapidfuzz.__version__ == {rapidfuzz.__version__}")
```

Output:

```
[[0 2 1 4]
 [2 0 3 2]
 [1 3 0 3]
 [4 2 3 0]]
[[0 1 1 3]
 [1 0 2 2]
 [1 2 0 2]
 [3 2 2 0]]
[[0 4 1 6]
 [4 0 5 2]
 [1 5 0 6]
 [6 2 6 0]]
rapidfuzz.__version__ == 2.13.4
```

The same call produced three different outputs. This behavior is intermittent -- you may need to run the script a couple times to reproduce it.

I'm not positive, but I think the issue lies in the input arguments being numpy arrays. I don't see this issue when I pass `list(arr)` instead:

```python
rapidfuzz.process.cdist(
    list(arr),
    list(arr),
    scorer=rapidfuzz.distance.Levenshtein.distance,
    weights=(1, 1, 1),
)
```

I'm using numpy version 1.22.0, if that helps.

**Comment by maxbachmann** [comment]
I was not able to reproduce the result differences. However I was able to identify two cases of undefined behavior when using `process.cdist` with numpy arrays. I assume those should lead to those incorrect results as well.

I just released `v2.13.5` which fixes these cases. Could you retry with the new release once the release CI is finished.

**Comment by maximz** [comment]
Thanks for the prompt reply! Yes, will test once CI completes

**Comment by maximz** [comment]
Works as expected now in v2.13.5. Thanks so much.
