### ISSUE TITLE
Non-standard function signature for `get_requires_for_build_wheel()`

### ISSUE THREAD

**Issue by troycurtisjr** [maxbachmann/rapidfuzz#303]
The function signature for `get_requires_for_build_wheel()` in `_custom_build/backend.py` has "self" as the first parameter, however [PEP 517](https://peps.python.org/pep-0517/#get-requires-for-build-wheel) lists it only with `config_settings`. The `setuptools.build_meta.get_requires_for_build_wheel` original implementation that this function "overrides" is actually a [bound method](https://github.com/pypa/setuptools/blob/main/setuptools/build_meta.py#L499), and thus doesn't take the `self` parameter.   

It seems like that function is being used somewhere, since it seems to be getting updates, but I haven't tracked it down exactly where that is.

**Comment by maxbachmann** [comment]
It appears you are correct. I opened a PR in setuptools to fix the corresponding documentation and will fix this in my build backend.

**Comment by maxbachmann** [comment]
I fixed this in https://github.com/maxbachmann/RapidFuzz/commit/8eadc371b09f25afd28737f7ad9b17a343da40e2. @troycurtisjr do you need a new release with this fix?

**Comment by troycurtisjr** [comment]
A new release would be great, but I can just apply a patch for now until a new release naturally happens.

**Comment by maxbachmann** [comment]
I created a new release with the fix. It will be available once the CI is finished (usually takes 2-3 hours)
