### ISSUE TITLE
wheel for intel 64 win archetecture

### ISSUE THREAD

**Issue by phillipboss** [maxbachmann/rapidfuzz#307]
hello i am interested in using the rapid fuzz library but found that it is not compatible for installation on a windows 10 system with a 64 bit intel processor. will there be a wheel for this anytime soon?

**Comment by maxbachmann** [comment]
There are already wheels for windows amd64: https://pypi.org/project/rapidfuzz/#files.

**Comment by phillipboss** [comment]
yes but they do not work for intel

**Comment by maxbachmann** [comment]
Well they should. How did you come to the conclusion, that they are not working for intel?

**Comment by phillipboss** [comment]
i think that it is not your wheel but my team lead telling me something incorrect. i tried the install myself and found that i do not have C ++ 14.0 installed and that is a requirement. i will have to talk to the IT department to get this escalated. sorry for the waste of time
