### ISSUE TITLE
Rapidfuzz in Docker with Python 3.11

### ISSUE THREAD

**Issue by carolienbraams** [maxbachmann/rapidfuzz#308]
The ReadMe of this RapidFuzz repo says it requires Python 3.7 or later. 
However, the pipenv command ran with a docker image with python 3.11 and fails to install rapidfuzz . 

Do others have this issue as well when using rapidfuzz==1.9.1 and Python 3.11?

**Comment by maxbachmann** [comment]
RapidFuzz 1.9.1 did not support Python 3.11 yet, since cython did require some changes to work on Python3.11. For this reason the first version with official support for Python 3.11 is version 2.4.4.
