### ISSUE TITLE
`NameError` with Cython 3.0.0b1

### ISSUE THREAD

**Issue by dotlambda** [maxbachmann/rapidfuzz#312]
With Cython 3.0.0b1 the tests fail with
```
NameError: name 'MatrixType' is not defined
```
See the [log](https://github.com/maxbachmann/RapidFuzz/files/10854059/log.txt).

**Comment by maxbachmann** [comment]
I will have a look into this later this week.

**Comment by maxbachmann** [comment]
I could reproduce the issue. I performed another test with the current main branch of Cython which works fine. So this appears to be one of the bugs introduced in `3.0.0b1`.

**Comment by maxbachmann** [comment]
The latest release is using cython 3.0.0b2 which fixes these issues.
