### ISSUE TITLE
Change of behaviour from 2.15.0 to 3.0.0 ??

### ISSUE THREAD

**Issue by dheerajck** [maxbachmann/rapidfuzz#322]
Hi,

I noticed a difference in the score in these two versions

rapidfuzz==2.15.0

```
>>> from rapidfuzz import fuzz
>>> a="a"
>>> fuzz.WRatio(a.lower(),a.upper())
100.0
```

rapidfuzz==3.0.0

```
>>> from rapidfuzz import fuzz
>>> a="a"
>>> fuzz.WRatio(a.lower(),a.upper())
0.0
>>> fuzz.WRatio(a.lower(),a.upper(), processor=utils.default_process)
100.0
```

Is this behaviour happening because inputs were preprocessed(converted to lower case or upper case ??) before and now its not done by default, or is it a bug

**Comment by maxbachmann** [comment]
Yes until version 3.0.0 it did preprocess the inputs by default. I changed this to make the behavior more consistent between the different metrics. In case you want to keep the old behavior you can simply pass the preprocessing function as you have done in your example.

I really need to update some of the documentation to make it more clear what the differences in behavior between rapidfuzz and thefuzz/fuzzywuzzy actually are, but I did not get around to it yet.

**Comment by dheerajck** [comment]
Hi,

https://github.com/maxbachmann/RapidFuzz/pull/324 
This pull request explains this behaviour in readme
