### ISSUE TITLE
ModuleNotFoundError: No module named 'rapidfuzz.string_metric'

### ISSUE THREAD

**Issue by shrey10926** [maxbachmann/rapidfuzz#325]
I have installed rapidfuzz using `pip install rapidfuzz`. If i try to import `from rapidfuzz.string_metric import levenshtein` I get the error. 
My python version is 3.8.0. OS is Ubuntu 20.04.

Any help would be appreciated!
Thanks in advance!

**Comment by maxbachmann** [comment]
The `string_metric` module was deprecated in v2.0.0 and removed in v3.0.0. You can use:
```python
from rapidfuzz.distance import Levenshtein
Levenshtein.distance(...)
```
instead
