### ISSUE TITLE
Not compatible with python 3.11

### ISSUE THREAD

**Issue by jeyboy26** [maxbachmann/rapidfuzz#326]
It is currently not compatible with python 3.11. To solve, I just created another env using: 
```
python3.9 -m venv venv
source venv/bin/activate
```
Thought I'd share.

**Comment by maxbachmann** [comment]
Which problem did you run into in Python 3.11? The package should work fine in Python 3.11. I do publish binary wheels for it as well.

**Comment by yurivict** [comment]
See the details in this [downstream bug report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=271382).

**Comment by maxbachmann** [comment]
This attempts to build a very old version of rapidfuzz (2.0.15) which was released before cpython 3.11 was released. Python 3.11 support was added in version 2.4.4.
