### ISSUE TITLE
broken docs

### ISSUE THREAD

**Issue by nonchris** [maxbachmann/rapidfuzz#327]
Heyo,
I wanted to fix it on my own and make a PR, but I can't find the place where the docs are actually written.
The problem lies [here](https://maxbachmann.github.io/RapidFuzz/Usage/process.html#rapidfuzz.process.cdist), more concrete in the explanation of the `scorer`. There is written
> "Further details can be found here"

But there is nothing clickable, what makes it kinda hard to find the other possibilities with explanation. I suppose it should reference to somewhere [here](https://maxbachmann.github.io/rapidfuzz-cpp/group__Fuzz.html), but I don't know.

Have a great day!
Chris

**Comment by maxbachmann** [comment]
I think this should just be updated to the same text used for process.extract/process.extractOne/...

In theory there is a C API which would allow users to write their own scorers, but in praxis this is not documented right now.

**Comment by maxbachmann** [comment]
I updated the docs to use the same description for the scorer argument in all functions.
