### ISSUE TITLE
Clarify default limit behaviour of rapidfuzz.process.extract

### ISSUE THREAD

**Issue by peterjc** [maxbachmann/rapidfuzz#328]
The documentation for extract says ``limit: int | None = None,`` and:

* limit (int) – maximum amount of results to return

https://maxbachmann.github.io/RapidFuzz/Usage/process.html#extract

That matches the function signature here:

https://github.com/maxbachmann/RapidFuzz/blob/v3.0.0/src/rapidfuzz/process_cpp_impl.pyi#L45

```python
@overload
def extract(
    query: _S1,
    choices: Collection[_S2],
    *,
    scorer: Callable[..., _ResultType] = WRatio,
    processor: Callable[..., _StringType] | None = None,
    limit: int | None = None,
    score_cutoff: _ResultType | None = None,
    **kwargs: Any,
) -> list[tuple[_S2, _ResultType, int]]: ...
```

I had read this and assumed the default was ``None``, and that meant no limit. i.e. Return all matches (passing the score_cuttoff if used).

Practical testing suggests the default limit is actually 5, which is also what #114 said (but that could possibly now out of date). That matches this function definition

https://github.com/maxbachmann/RapidFuzz/blob/v3.0.0/src/rapidfuzz/process_cpp_impl.pyx#L953

```
def extract(query, choices, *, scorer=WRatio, processor=None, limit=5, score_cutoff=None, score_hint=None, scorer_kwargs=None):
```

In my case as a workaround I can probably use ``limit=len(choices)`` for no limit - performance impact for my use-case to be assessed.

**Comment by maxbachmann** [comment]
The typing and documentation are both incorrect :sweat_smile: 
You are right that similar to `fuzzywuzzy` the default value is actually 5. You can disable the behaviour by passing `limit=None` which is equivalent to `limit=len(choices)` .

https://github.com/maxbachmann/RapidFuzz/commit/8d8a80790a8bdfe81793d78ff08a04bffbc75738 should fix the type hints and documentation for this.

**Comment by peterjc** [comment]
That's a better solution (passing ``limit=None``), but does it actually work for you?

I'm struggling to cut down my test case (still over 3000 entries), but I think using ``limit=None`` has no effect under v3.0.0.

**Comment by maxbachmann** [comment]
Yes it does work for me:
```
>>> import rapidfuzz
>>> from rapidfuzz import process
>>> rapidfuzz.__version__
'3.0.0'
>>> process.extract("a", ["a", "b"]*5, limit=None)
[('a', 100.0, 0), ('a', 100.0, 2), ('a', 100.0, 4), ('a', 100.0, 6), ('a', 100.0, 8), ('b', 0.0, 1), ('b', 0.0, 3), ('b', 0.0, 5), ('b', 0.0, 7), ('b', 0.0, 9)]
```

**Comment by peterjc** [comment]
Thanks. I will keep digging on my side. That example also worked on 2.11.0 (one of the machines I am using had an older version).

OK to close this issue?

**Comment by maxbachmann** [comment]
Yes in case you find a reproducing example of it not working you can just open a new issue on this :+1:

**Comment by peterjc** [comment]
Working for me now - thank you!
