### ISSUE TITLE
error: function 'tf::FlowBuilder::for_each_index<long, long, long, (lambda at /usr/ports/devel/py-rapidfuzz/work-py39/rapidfuzz-3.0.0/src/rapidfuzz/process_cpp.hpp:414:58), tf::GuidedPartitioner>' is used but not defined in this translation unit, and cannot be defined in any other translation unit because its type does not have linkage

### ISSUE THREAD

**Issue by yurivict** [maxbachmann/rapidfuzz#329]
Build fails on some machines with the error from the subject.

[log](https://people.freebsd.org/~yuri/py39-rapidfuzz-3.0.0.log)

FreeBSD 13.2

**Comment by maxbachmann** [comment]
This was a breaking change in the taskflow 3.6 release. Apparently taskflow is not actually compatible between minor version releases.

**Comment by yurivict** [comment]
I have taskflow-3.6.0

**Comment by maxbachmann** [comment]
Yes I will need to change the code in rapidfuzz to be compatible with taskflow 3.6

**Comment by maxbachmann** [comment]
This should be fixed in `v3.1.1`
