### ISSUE TITLE
error: 'isnan' was not declared in this scope; did you mean 'std::isnan'

### ISSUE THREAD

**Issue by 0-wiz-0** [maxbachmann/rapidfuzz#330]
Building the C extension on NetBSD, I noticed the error
```
error: 'isnan' was not declared in this scope; did you mean 'std::isnan'
```
occurring a couple of times during the build.
Replacing 'isnan' with 'std::isnan' fixes the problem for me.

**Comment by maxbachmann** [comment]
Interesting I do include math.h, so it should exist. Really not sure why it does not. Still would be cleaner to use std::isnan here anyway, so I guess we can just avoid the issue.

**Comment by maxbachmann** [comment]
This should be fixed in `v3.1.1`

**Comment by 0-wiz-0** [comment]
Thank you!
Can you please upload it to pypi?

**Comment by maxbachmann** [comment]
It is automatically uploaded once the ci build (https://github.com/maxbachmann/RapidFuzz/actions/runs/5188558618) is finished

**Comment by 0-wiz-0** [comment]
Just to confirm - 3.1.1 does indeed fix the problem I was seeing. Thanks!
