### ISSUE TITLE
document API differences with `fuzzywuzzy`

### ISSUE THREAD

**Issue by maxbachmann** [maxbachmann/rapidfuzz#333]
At this point there are a couple differences in the API which should be documented.

**Comment by maxbachmann** [comment]
@banagale I added  https://github.com/maxbachmann/RapidFuzz/blob/main/api_differences.md which documents all API differences I know of the top of my head.

**Comment by banagale** [comment]
Thanks a lot for this, Max. 

I think I did a CMD-F for `extractBests` in the package using my IDE trying to solve my own problem before posting my issue. 

I had thought it came back with nothing, so this addition would likely have answered my question.
