### ISSUE TITLE
Consider using the stable API 

### ISSUE THREAD

**Issue by maxbachmann** [maxbachmann/rapidfuzz#340]
switching to the minimal C-API would drastically reduce the amount of binaries we need to build. 
1) get branch to build with minimal API. This should largely be a  config thing, since I think cython, scikit-build and cibuildwheel all support the stable API at this point (not supported for PyPy)
2) test the performance impact. I expect it to be very small for everything except `array` conversion which is a very niche usage.

**Comment by maxbachmann** [comment]
Cyhon does not support the limited Python API yet. Even when it does it will likely have a pretty large performance overhead for the time being.

**Comment by Avasam** [comment]
Cython should support it as of 3.1: https://docs.cython.org/en/latest/src/userguide/limited_api.html#
Which had already been bumped along with free-threading support: https://github.com/rapidfuzz/RapidFuzz/commit/5a30db2f9412907bc087fb4e3238d3ac946c28f5

The possible performance concerns are still present (untested). Apparently dropping Python 3.11 support [would] "give a noticeable performance improvement" for Limited API mode: https://docs.cython.org/en/latest/src/userguide/limited_api.html#performance
