### ISSUE TITLE
Feature Request: Computing the distance/similarity for 2 lists of same length

### ISSUE THREAD

**Issue by thomasryde** [maxbachmann/rapidfuzz#344]
Would it be possible to write a function that computes the similarity between the corresponding elements of 2 lists of equal length?

I am hoping for a ridiculous speed-up of this operation compared to doing it element by element in python. I guess this request would be like cdist() but just for corresponding elements of 2 lists instead of all combinations. Love the library.

**Comment by thomasryde** [comment]
Hi @maxbachmann

I am considering to make a PR with this and call it pdist (for pairwise distance under the process folder). Is this a feature you believe would be beneficial to the project and do you have any opinion on the location? /Thomas

**Comment by maxbachmann** [comment]
With https://github.com/rapidfuzz/RapidFuzz/commit/34f1976f2b154532a241e0afc1e5f524dbc6fb94 and https://github.com/rapidfuzz/RapidFuzz/commit/34f1976f2b154532a241e0afc1e5f524dbc6fb94 the string conversions is down from around 130ns to around 77ns per string pair.

**Comment by maxbachmann** [comment]
https://github.com/rapidfuzz/RapidFuzz/commit/6c5b37fe25b902b08407a1b71456e5d5a1d1ba68 is another improvement for the matching. This reduces the runtime of the second part from 90ns down to 59ns for single threaded execution.

I think this concludes the more obvious performance improvements.
