### ISSUE TITLE
Question: different outcome from partial_ratio and ratio

### ISSUE THREAD

**Issue by koenvanbenthem** [maxbachmann/rapidfuzz#345]
I am somehow stuck on the difference between partial_ratio and ratio - probably I am having silly misunderstanding. When I run:
```
import rapidfuzz.fuzz as rfuzz
rfuzz.partial_ratio("toad","goat")
```
I get a value of 57.14285714285714
While:
`rfuzz.ratio("toad","goat")`
returns 50.0. As far as I understood the documentation, both should return 50.0. Can you help me understand what I am misunderstanding?

Thank you for your time!

edit: I'm using rapidfuzz 3.2.0 on Python 3.9.13

**Comment by koenvanbenthem** [comment]
I think I just understood what is going on:
although the shorter string is always kept the same length, it is compared against a sliding window of variable length in the longer string. (I was somehow expecting a sliding window of the same constant length as well).

In this case both are equally long, so we can freely pick which one is the longer. Let's pick toad as the short one.
Now it finds the best alignment for toad <> goa 

The similarity for this comparison is (1 substitution, 1 deletion): 1 - (2+1)/(3+4) =  0.5714286

Interestingly enough, when adding one character at the beginning and one at the and of the longer string, the partial ratio become 0.50 (because the shorter windows are only evaluated at the beginning and the end of the character string):
`rfuzz.partial_ratio("toad","(goat)")`
returns 0.50, because toad is not compared against goa or oat, but only against the shorter windows (go and at).

**Comment by maxbachmann** [comment]
Yes it is using a sliding window of the length of the shorter string. This window can be shorter when it is placed at the start/end of the longer string. When both strings have the same length it will calculate the similarity in both directions and returns the higher similarity. This is done to ensure `partial_ratio(a, b) == partial_ratio(b, a)`.

You can use `fuzz.partial_ratio_alignment` to retrieve both the similarity and the alignment/window used to achieve this similarity.
