### ISSUE TITLE
Feature request: Handle pd.NA

### ISSUE THREAD

**Issue by philipnye** [maxbachmann/rapidfuzz#349]
Would you consider adding support for `pd.NA`, handling it like `np.nan` (as described here #291)? I appreciate that `pd.NA` is currently experimental.

**Comment by maxbachmann** [comment]
Yes it makes sense to handle `pd.NA` similar to `np.nan`. I added support for this in https://github.com/maxbachmann/RapidFuzz/commit/ac83d6ade6ae59a1118c4324114b4adf8106eed4
