### ISSUE TITLE
fuzz_py.token_set_ratio and fuzz.token_set_ratio have different results

### ISSUE THREAD

**Issue by BeanWei** [maxbachmann/rapidfuzz#353]
```shell
>>> fuzz_py.token_set_ratio("js", "vue js")
80.0
>>> fuzz.token_set_ratio("js", "vue js")
100.0
```

**Comment by maxbachmann** [comment]
Thanks for reporting. This is a bug in the pure python fallback implementation of token_set_ratio. I fixed it in https://github.com/maxbachmann/RapidFuzz/commit/9993c17aebbb82b021e1e4b90369ca32ece7e1bc
