### ISSUE TITLE
AttributeError: module 'rapidfuzz.process' has no attribute 'cpdist'

### ISSUE THREAD

**Issue by Alireza-G-Qre** [maxbachmann/rapidfuzz#376]
I got the latest version of the library, but I get the following error:

AttributeError                            Traceback (most recent call last)
Cell In [55], line 3
      1 from rapidfuzz import process
----> 3 process.cpdist

AttributeError: module 'rapidfuzz.process' has no attribute 'cpdist'

**Comment by maxbachmann** [comment]
Are you sure you are using the latest version?
```python
>>> import rapidfuzz
>>> rapidfuzz.__version__
'3.8.1'
```
The error sounds very much like you are still on an older version :thinking:
