### ISSUE TITLE
Please add support for newer versions of TaskFlow

### ISSUE THREAD

**Issue by mgorny** [maxbachmann/rapidfuzz#385]
RapidFuzz currently allows using only TaskFlow 3.3:

https://github.com/rapidfuzz/RapidFuzz/blob/cb8a1b112ab38d1b1119abb36de7c621bd47322a/CMakeLists.txt#L76

Could you please allow newer versions as well? FWICS 3.7.0 still works fine (or at least builds cleanly and tests pass).

**Comment by maxbachmann** [comment]
newer versions certainly work. In fact I am packaging with v3.7.0 on pypi.
So this is simply an incorrect specification in the cmake file.

**Comment by maxbachmann** [comment]
Should be fixed

**Comment by mgorny** [comment]
Thanks! Kinda sucks version ranges don't work there.

**Comment by maxbachmann** [comment]
Yes I believe due to the compatibility setting of taskflow on minor versions it has to be explicit.

Could probably be a function looping over versions to check them, but I am not super familiär with cmake. So I will look into it when the list gets too long
