### ISSUE TITLE
Migration to `scikit-build-core`

### ISSUE THREAD

**Issue by LecrisUT** [maxbachmann/rapidfuzz#390]
It is recommended that projects migrate from `scikit-build` to `scikit-build-core` when possible. Most development is focused there and it is a very CMake friendly and pythonic build system. For now I only wanted to create an issue to get your opinion on this and track the progress of such migration. If you have questions or need help, feel free to ask.

**Comment by maxbachmann** [comment]
This is done in https://github.com/rapidfuzz/RapidFuzz/pull/397
