### ISSUE TITLE
Documentation error for rapidfuzz.fuzz.process.ratio

### ISSUE THREAD

**Issue by ai-robert** [maxbachmann/rapidfuzz#393]
[The documentation](https://rapidfuzz.github.io/RapidFuzz/Usage/fuzz.html#rapidfuzz.fuzz.ratio) for rapidfuzz.fuzz.process.ratio 
[here](https://github.com/rapidfuzz/RapidFuzz/blob/e42836a0479b7489b776434631d1e5d7845f018b/src/rapidfuzz/fuzz_py.py#L73) and [here](https://github.com/rapidfuzz/RapidFuzz/blob/e42836a0479b7489b776434631d1e5d7845f018b/src/rapidfuzz/fuzz_py.py#L96)
contradict what the code actually does
[here](https://github.com/rapidfuzz/RapidFuzz/blob/e42836a0479b7489b776434631d1e5d7845f018b/src/rapidfuzz/fuzz_py.py#L114)

Solution:
s/Indel distance/Indel similarity/g

**Comment by maxbachmann** [comment]
Thanks for reporting. I updated the documentation
