### ISSUE TITLE
Gentoo libcxx-19 build failure (implicit instantiation of undefined template 'std:char_traits<unsigned char>')

### ISSUE THREAD

**Issue by HyperWinX** [maxbachmann/rapidfuzz#415]
Hi, noticed that issue after upgrading to libcxx-19 and trying to emerge poetry. 
```
In file included from /home/hyperwin/d/project_build/RapidFuzz/build/src/rapidfuzz/utils_cpp.cxx:1240:
In file included from /usr/include/c++/v1/ios:220:
In file included from /usr/include/c++/v1/__locale:24:
/usr/include/c++/v1/string:2864:5: error: implicit instantiation of undefined template 'std::char_traits<unsigned int>'
 2864 |     traits_type::assign(__p[__sz], value_type());
      |     ^
/usr/include/c++/v1/__fwd/string.h:23:29: note: template is declared here
   23 | struct _LIBCPP_TEMPLATE_VIS char_traits;
      |                             ^
```

After doing some research, i found out that libcxx-19 removed support for non-standard types in std::char_traits. The main issue is that this file (utils_cpp.cxx) is generated by Cython, and probably can't be fixed from RapidFuzz source code. Enabling C++20/C++23 changed nothing. 
Useful links about related issues:
https://reviews.llvm.org/D138307
https://bugs.gentoo.org/939897#c0
https://github.com/zxing-cpp/zxing-cpp/pull/836
https://en.cppreference.com/w/cpp/string/char_traits

**Comment by maxbachmann** [comment]
I will have a look at this. This should be a relatively straightforward fix

**Comment by maxbachmann** [comment]
I believe one of the distros already did their own path for this issue in `rapidfuzz-cpp`

**Comment by HyperWinX** [comment]
Oh, i see, there is a fork. But the problem is that poetry (or one of it's dependencies) probably depends on rapidfuzz, and not on rapidfuzz-cpp. I'll try tho

**Comment by maxbachmann** [comment]
What I did mean is that RapidFuzz uses rapidfuzz-cpp. They already wrote a workaround for rapidfuzz-cpp but not for Rapidfuzz.

I will release a proper fix later today.

**Comment by HyperWinX** [comment]
Okay, thank you so much. I just noticed that dev-python/rapidfuzz has opened bug on the same issue.

**Comment by maxbachmann** [comment]
I published rapidfuzz-cpp v3.1.1 which should allow dropping the patches made for it in gentoo. In addition I published Rapidfuzz v3.10.1 which should fix the same issue in the python wrapper.

**Comment by HyperWinX** [comment]
Okay, i will test it and report back if it fixes the issue.

**Comment by HyperWinX** [comment]
Confirming fix. Waiting for ebuild update.
